[package]
name = "spell-combinator"
version = "0.1.0"
authors = ["Anders Thun√© <asse.97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
